name: Spark Test Server Deploy
on:
  push:
    branches: [test]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Create firebase-sdk file
      - name: Create Firebase SDK File
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "we-sopt-spark-firebase-adminsdk-emnjd-30d5170309.json"
          json: ${{ secrets.FIREBASE_SDK }}
          dir: "functions/"

      # Create .env file
      - name: Create .env
        run: |
          touch ./functions/.env
          echo "${{ secrets.DOT_ENV }}" > ./functions/.env
        shell: bash

      # Update .firebaserc file
      - name: Update .firebaserc
        run: |
          rm .firebaserc
          touch .firebaserc
          echo "${{ secrets.FIREBASE_RC }}" > .firebaserc
        shell: bash

      # Replace firebaseClient Config file
      - name: Replace FirebaseClient Config file
        run: |
          rm ./functions/config/firebaseClient.js
          touch ./functions/config/firebaseClient.js
          echo "${{ secrets.TEST_SERVER_FIREBASE_CLIENT }}" > ./functions/config/firebaseClient.js
        shell: bash

      - name: Install npm packages
        run: |
          cd functions
          npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions --project spark-test-server
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
